spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_jwt
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  application:
    name: service-provider
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8000/eureka/

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: me.freelee.commonutil.model
server:
  port: 8081
